// packages/zfilesystem/tsup.config.ts
import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: { index: "src/index.ts" },
    format: ["esm", "cjs"],
    dts: true,
    sourcemap: true,
    clean: true,
    outDir: "dist",
    target: "es2020",
    platform: "browser",
    splitting: false,
    treeshake: true,
    minify: false,
    outExtension: ({ format }) => ({ js: format === "cjs" ? ".cjs" : ".mjs" }),
  },
  {
    entry: { "zeos-zfilesystem": "src/index.ts" },
    format: ["esm"],
    dts: false,
    sourcemap: true,
    clean: false,
    outDir: "dist",
    target: "es2020",
    platform: "browser",
    splitting: false,
    treeshake: true,
    minify: false,
    outExtension: () => ({ js: ".js" }),
  },
  {
    entry: { "zeos-zfilesystem.min": "src/index.ts" },
    format: ["esm"],
    dts: false,
    sourcemap: true,
    clean: false,
    outDir: "dist",
    target: "es2020",
    platform: "browser",
    splitting: false,
    treeshake: true,
    minify: true,
    outExtension: () => ({ js: ".js" }),
  },
  {
    entry: { "zeos-zfilesystem.global": "src/global.ts" },
    format: ["iife"],
    globalName: "ZEOSZFilesystem",
    dts: false,
    sourcemap: true,
    clean: false,
    outDir: "dist",
    target: "es2020",
    platform: "browser",
    splitting: false,
    treeshake: true,
    minify: false,
    outExtension: () => ({ js: ".js" }),
  },
]);
